[package]
name = "agora-threshold-sig"
version = "0.1.0"
edition = "2021"

[dependencies]
bls = { package = "bls12_381", version = "0.7.0", features = ["experimental"] }
ff = "0.12"
generic-array = "0.14"
group = "0.12"
rand_core = "0.6.0"
sha3 = "0.9"
zeroize = "1.5.7"
