[package]
name = "agora-interpolate"
version = "0.1.0"
edition = "2021"

[features]
k256-scalar = ["k256"]
bls-scalar = ["bls"]

[dependencies]
bls = { package = "bls12_381", version = "0.6.0", optional = true}
k256 = { version = "0.11", optional = true }
subtle = "2.4.1"
thiserror = "1.0"
